#!/bin/sh
# Wrapper installe dans /usr/bin/netcross-batch par le paquet Debian/RPM.
export PYTHONPATH="/usr/share/netcross:${PYTHONPATH:-}"
exec /usr/bin/python3 /usr/share/netcross/cross_capture_batch_cli.py "$@"
